name: foundation
description: A new Flutter package project.
version: 0.0.1
author:
homepage: ' '

environment:
  flutter: 2.2.2
  sdk: ">=2.13.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0
  timeago: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
