# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new development version to the Firebase App Distribution"
  lane :deploy_development_to_firebase do
    firebase_app_distribution(
        app: ENV['DEVELOPMENT_ANDROID_FIREBASE_APP_ID'],
        apk_path: "../build/app/outputs/apk/development/debug/app-development-debug.apk",
        groups: "beta-testers",
        release_notes: ""
    )
  end
end
